# Generated by Django 4.1.6 on 2023-05-08 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('imageUrl', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=55)),
                ('lastName', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('imageUrl', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('imageUrl', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('imageUrl', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ArtBex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(max_length=200)),
                ('audience', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artbexapi.audience')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artbexapi.creator')),
                ('format', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artbexapi.format')),
                ('production', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artbexapi.production')),
                ('tone', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artbexapi.tone')),
            ],
        ),
    ]
