# Generated by Django 4.1.6 on 2023-04-09 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtBex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('imageUrl', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=55)),
                ('lastName', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('imageUrl', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('imageUrl', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
                ('imageUrl', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ArtbexProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artbex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artbex_production', to='artbexapi.artbex')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_artbex', to='artbexapi.production')),
            ],
        ),
        migrations.CreateModel(
            name='ArtbexFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artbex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artbex_format', to='artbexapi.artbex')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_artbex', to='artbexapi.format')),
            ],
        ),
        migrations.CreateModel(
            name='ArtbexAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artbex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artbex_audience', to='artbexapi.artbex')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_artbex', to='artbexapi.audience')),
            ],
        ),
        migrations.AddField(
            model_name='artbex',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artbexapi.creator'),
        ),
        migrations.AddField(
            model_name='artbex',
            name='tone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artbexapi.tone'),
        ),
    ]
