# Generated by Django 4.1.6 on 2023-06-15 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artbexapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artbeximage',
            name='artbex',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='artbex_image', to='artbexapi.artbex'),
        ),
        migrations.AlterField(
            model_name='artbeximage',
            name='image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_artbex', to='artbexapi.image'),
        ),
    ]
